export const SHOW_PRODUCT = 'SHOW_PRODUCT';
export const ADD_TO_CART = 'ADD_TOO_CART'
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE'
export const DELETED_TO_CART = 'DELETED_TO_CART'
export const UPDATE_AMOUNT_IN_PRODUCT = 'UPDATE_AMOUNT_IN_PRODUCT'